### PR TITLE
Add support for multiple definitions

### PR DESCRIPTION
**Pull request by av3r4ge**
#11

### CODE REVIEW

**Comment by beloglazov** [comment]
Thanks for this PR! However, I hesitate merging it in as I'm not familiar with Perl and maintaining this new code would be hard for me. Do you think it would be possible to implement this in awk/sed?

**Comment by av3r4ge** [comment]
That's understandable.
I'm not really familliar with awk/sed. I use them just for small and trivial work.
I guess it can be done with them.
I can take a look a bit more at awk/sed and try to implement it that way, though it'll take me some time.

**Comment by av3r4ge** [comment]
Ok. I split the result transformation to two parts: Shell part and Vim part.
I hope it's easier to maintain :)

**Comment by beloglazov** [comment]
Awesome, that was quick, thanks! :)

**Comment by av3r4ge** [comment]
Well, That's embarrassing.
When I tested it, it seemed to do the right thing, so I haven't noticed the missing backslashes.
I also usually use single quotes which doesn't need escaping.
Sorry for this.

**Comment by beloglazov** [comment]
No worries, I've fixed it. Does the current version work well for you?

**Comment by av3r4ge** [comment]
Sure :)

**Comment by beloglazov** [comment]
:+1:

**Pull request merged**
